version: '3.8'

services:
  voting-system:
    build: .
    ports:
      - "${EXTERNAL_PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes: []
      # 如果需要持久化資料，可以取消註解下面這行
      # - ./data:/app/data
    networks:
      - voting-network

networks:
  voting-network:
    driver: bridge